const Joi = require("joi");

exports.propertySchema = Joi.object({
  title: Joi.string().required(),
  description: Joi.string().required(),
  area: Joi.number().required(),
  price: Joi.number().required(),
  listingType: Joi.string().valid("SELL", "RENT"),
  address: Joi.string().required(),
  lat: Joi.number().required(),
  lng: Joi.number().required(),
  storey: Joi.number().integer().optional(),
  bedroom: Joi.number().integer().optional(),
  bathroom: Joi.number().integer().optional(),
  livingroom: Joi.number().integer().optional(),
  kitchen: Joi.number().integer().optional(),
  airconditioner: Joi.number().integer().optional(),
  parking: Joi.number().integer().optional(),
  security: Joi.boolean().required(),
  club: Joi.boolean().required(),
  pool: Joi.boolean().required(),
  gym: Joi.boolean().required(),
  playground: Joi.boolean().required(),
  park: Joi.boolean().required(),
  elevator: Joi.boolean().required(),
  categoryId: Joi.number().integer().required(),
  provinceId: Joi.number().integer().required(),
  districtId: Joi.number().integer().required(),
  roadId: Joi.number().integer().required(),
});
